import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PlaceholderImage } from "@/components/placeholder-image";
import { SectionHeading } from "@/components/section-heading";
const procedures=[{name:"Lipo 360",type:"Body contouring",href:"/procedures#lipo"},{name:"BBL",type:"Body contouring",href:"/procedures#bbl"},{name:"J-Plasma",type:"Skin tightening",href:"/procedures#jplasma"},{name:"Chin Liposuction",type:"Facial contouring",href:"/procedures#chin"},{name:"Injectables",type:"Non-surgical aesthetics",href:"/procedures#injectables"},{name:"FUE Hair Transplant",type:"Hair restoration",href:"/hair-restoration"}];
export default function Home(){return <main><section className="relative min-h-[760px] overflow-hidden bg-[#cfc1b5] pt-20"><PlaceholderImage className="absolute inset-0 h-full w-full" label="Hero photography placeholder — replace with approved clinic imagery"/><div className="absolute inset-0 bg-gradient-to-r from-[#302821]/65 via-[#302821]/20 to-transparent"/><div className="relative mx-auto flex min-h-[680px] max-w-[1400px] items-end px-5 pb-20 md:px-8 md:pb-24"><div className="max-w-3xl text-white"><p className="eyebrow text-white/70">Plastic & Aesthetic Surgery · Atlanta</p><h1 className="serif mt-5 text-6xl leading-[.92] md:text-8xl">The art of<br/><em className="font-normal">refined confidence.</em></h1><p className="mt-7 max-w-xl text-sm leading-7 text-white/80 md:text-base">Thoughtful surgical and non-surgical care designed around your anatomy, goals, and individual journey.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link href="/contact">Schedule Consultation <ArrowUpRight size={16}/></Link></Button><Button asChild size="lg" variant="outline" className="border-white/40 text-white hover:bg-white hover:text-[#302821]"><Link href="/about">Meet Dr. Ladipo</Link></Button></div></div></div></section>
<section className="section-pad"><div className="container-xl grid gap-14 md:grid-cols-[1fr_1.3fr] md:items-end"><div><p className="eyebrow text-[#7d6d60]">The Ladipo Effect</p><h2 className="serif mt-5 text-5xl leading-none md:text-7xl">Precision.<br/>Proportion.<br/><i>Personalization.</i></h2></div><div><p className="text-lg leading-8 text-[#302821]/75">Every treatment begins with understanding the person, not simply the procedure. Dr. Ladipo combines surgical training, aesthetic judgment, and individualized planning to create a considered treatment experience.</p><Link href="/about" className="mt-8 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.15em]">Discover the philosophy <ArrowDownRight size={16}/></Link></div></div></section>
<section className="bg-[#e8ded3] section-pad"><div className="container-xl"><SectionHeading eyebrow="Featured treatments" title="Surgical & non-surgical options" description="Explore a focused range of body contouring, facial aesthetics, skin tightening, hair restoration, and wellness services."/><div className="mt-14 grid gap-px bg-[#302821]/15 sm:grid-cols-2 lg:grid-cols-3">{procedures.map((p,i)=><Link href={p.href} key={p.name} className="group bg-[#e8ded3] p-7 transition hover:bg-[#f7f3ee]"><div className="flex items-start justify-between"><span className="text-xs text-[#7d6d60]">0{i+1}</span><ArrowUpRight size={18} className="opacity-40 transition group-hover:translate-x-1 group-hover:-translate-y-1"/></div><h3 className="serif mt-20 text-3xl">{p.name}</h3><p className="mt-2 text-xs uppercase tracking-[.13em] text-[#302821]/50">{p.type}</p></Link>)}</div></div></section>
<section className="section-pad"><div className="container-xl grid gap-12 md:grid-cols-[.9fr_1.1fr] md:items-center"><PlaceholderImage className="aspect-[4/5]" label="Approved Dr. Ladipo portrait placeholder"/><div className="md:pl-10"><p className="eyebrow text-[#7d6d60]">Meet Dr. Ladipo</p><h2 className="serif mt-5 text-5xl md:text-6xl">A global surgical perspective, grounded in individualized care.</h2><p className="mt-7 text-sm leading-7 text-[#302821]/65">Olanrewaju Ladipo, MD, has pursued medical and surgical training across multiple continents, with experience spanning internal medicine, reconstructive microsurgery, and plastic surgery.</p><p className="mt-5 text-sm leading-7 text-[#302821]/65">His practice focuses on body and facial procedures, aesthetic medicine, hair restoration, and regenerative approaches.</p><Button asChild variant="outline" className="mt-8"><Link href="/about">Read Dr. Ladipo's story</Link></Button></div></div></section>
<section className="bg-[#302821] px-5 py-20 text-[#f7f3ee] md:px-8 md:py-28"><div className="container-xl grid gap-12 md:grid-cols-[1fr_auto] md:items-end"><div><p className="eyebrow text-white/45">Hair & regenerative medicine</p><h2 className="serif mt-4 max-w-3xl text-5xl leading-tight md:text-7xl">New pathways to restoration, with a personalized plan.</h2></div><Button asChild variant="outline" size="lg" className="border-white/30 text-white hover:bg-white hover:text-[#302821]"><Link href="/hair-restoration">Explore treatments <Sparkles size={16}/></Link></Button></div></section>
<section className="section-pad"><div className="container-xl"><SectionHeading eyebrow="Your journey" title="From consultation to care" align="center"/><div className="mt-14 grid gap-8 md:grid-cols-4">{[["01","Consultation","Discuss your goals, anatomy, history, and options."],["02","Plan","Build a treatment approach tailored to you."],["03","Care","Receive attentive care throughout your procedure or treatment."],["04","Follow-up","Track healing and progress with appropriate follow-up."]].map(([n,t,d])=><div key={n} className="border-t border-[#302821]/15 pt-5"><span className="text-xs text-[#9a8879]">{n}</span><h3 className="serif mt-8 text-2xl">{t}</h3><p className="mt-3 text-sm leading-6 text-[#302821]/60">{d}</p></div>)}</div></div></section>
<section className="bg-[#d8c9bd] px-5 py-24 text-center md:px-8"><div className="mx-auto max-w-3xl"><p className="eyebrow text-[#7d6d60]">Begin with a conversation</p><h2 className="serif mt-5 text-5xl md:text-7xl">Your aesthetic journey starts here.</h2><p className="mx-auto mt-6 max-w-xl text-sm leading-7 text-[#302821]/65">Schedule a consultation to discuss your goals and learn which options may be appropriate for you.</p><Button asChild size="lg" className="mt-8"><Link href="/contact">Schedule Consultation</Link></Button></div></section></main>}
